-- MySQL Script generated by MySQL Workbench
-- vie 22 nov 2019 16:37:44 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RiesgosNaturales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RiesgosNaturales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RiesgosNaturales` DEFAULT CHARACTER SET utf8 ;
USE `RiesgosNaturales` ;

-- -----------------------------------------------------
-- Table `RiesgosNaturales`.`TipoVialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RiesgosNaturales`.`TipoVialidad` ;

CREATE TABLE IF NOT EXISTS `RiesgosNaturales`.`TipoVialidad` (
  `idTipoVialidad` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idTipoVialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiesgosNaturales`.`Ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RiesgosNaturales`.`Ubicacion` ;

CREATE TABLE IF NOT EXISTS `RiesgosNaturales`.`Ubicacion` (
  `idUbicacion` INT NOT NULL AUTO_INCREMENT,
  `nombreVialidad` VARCHAR(25) NOT NULL,
  `numeroExterior` VARCHAR(25) NULL,
  `idTipoVialidad` INT NOT NULL,
  PRIMARY KEY (`idUbicacion`),
  INDEX `idTipoVialidad_idx` (`idTipoVialidad` ASC),
  CONSTRAINT `idTipoVialidad`
    FOREIGN KEY (`idTipoVialidad`)
    REFERENCES `RiesgosNaturales`.`TipoVialidad` (`idTipoVialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiesgosNaturales`.`Edificio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RiesgosNaturales`.`Edificio` ;

CREATE TABLE IF NOT EXISTS `RiesgosNaturales`.`Edificio` (
  `idEdificio` INT NOT NULL AUTO_INCREMENT,
  `nombreEdificio` VARCHAR(25) NULL,
  `usoSuelo` VARCHAR(25) NOT NULL,
  `cuentaCatastral` FLOAT NULL,
  `idUbicacion` INT NOT NULL,
  PRIMARY KEY (`idEdificio`),
  INDEX `idUbicacion_idx` (`idUbicacion` ASC),
  CONSTRAINT `idUbicacion`
    FOREIGN KEY (`idUbicacion`)
    REFERENCES `RiesgosNaturales`.`Ubicacion` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiesgosNaturales`.`NivelDaño`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RiesgosNaturales`.`NivelDaño` ;

CREATE TABLE IF NOT EXISTS `RiesgosNaturales`.`NivelDaño` (
  `idNivelDaño` INT NOT NULL AUTO_INCREMENT,
  `nombreNivel` VARCHAR(0) NOT NULL,
  PRIMARY KEY (`idNivelDaño`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiesgosNaturales`.`Daño`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RiesgosNaturales`.`Daño` ;

CREATE TABLE IF NOT EXISTS `RiesgosNaturales`.`Daño` (
  `idDaño` INT NOT NULL AUTO_INCREMENT,
  `tipoDaño` VARCHAR(25) NOT NULL,
  `idNivelDaño` INT NOT NULL,
  PRIMARY KEY (`idDaño`),
  INDEX `idNivelDaño_idx` (`idNivelDaño` ASC),
  CONSTRAINT `idNivelDaño`
    FOREIGN KEY (`idNivelDaño`)
    REFERENCES `RiesgosNaturales`.`NivelDaño` (`idNivelDaño`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RiesgosNaturales`.`EdificioSufreDaño`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RiesgosNaturales`.`EdificioSufreDaño` ;

CREATE TABLE IF NOT EXISTS `RiesgosNaturales`.`EdificioSufreDaño` (
  `idEdificioSufreDaño` INT NOT NULL AUTO_INCREMENT,
  `idDaño` INT NOT NULL,
  `idEdificio` INT NOT NULL,
  PRIMARY KEY (`idEdificioSufreDaño`),
  INDEX `idEdificio_idx` (`idEdificio` ASC),
  INDEX `idDaño_idx` (`idDaño` ASC),
  CONSTRAINT `idEdificio`
    FOREIGN KEY (`idEdificio`)
    REFERENCES `RiesgosNaturales`.`Edificio` (`idEdificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDaño`
    FOREIGN KEY (`idDaño`)
    REFERENCES `RiesgosNaturales`.`Daño` (`idDaño`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
